dev.mtpeter.rsq:
  tenants:
    tenantA:
      username: test
      password: test
      url: r2dbc:postgresql://localhost/tenantA
    tenantB:
      username: test
      password: test
      url: r2dbc:postgresql://localhost/tenantB
logging:
  level:
    root: debug